# Generated by Django 4.2.6 on 2023-11-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_owner_inventory_item_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='about',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='title',
        ),
    ]
