# Generated by Django 4.2.6 on 2023-11-20 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_remove_inventory_about_remove_inventory_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='owner',
        ),
        migrations.AddField(
            model_name='owner',
            name='inventory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_app.inventory'),
        ),
    ]
