# Generated by Django 4.2.6 on 2023-11-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0006_alter_item_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(to='inventory_app.tag'),
        ),
    ]
