# Generated by Django 4.2.6 on 2023-11-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0007_alter_item_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='insurance',
            field=models.CharField(blank=True, choices=[('StateFarm', 'State Farm'), ('Allstate', 'Allstate'), ('USAA', 'USAA'), ('Lemonade', 'Lemonade'), ('Nationwide', 'Nationwide'), ('LibertyMutual', 'Liberty Mutual'), ('Travelers', 'Travelers')], max_length=100, null=True),
        ),
    ]
